"""initial schema with indexes and invite expires_at

Revision ID: 696891ea714f
Revises: 
Create Date: 2026-03-12 21:33:18.210791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696891ea714f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index('ix_followups_status', ['status', 'level'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.create_index('ix_replies_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.create_index('ix_sends_user_sent', ['user_id', 'sent_at'], unique=False)

    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index('ix_usage_user_date', ['user_id', 'period_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_user_date')

    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.drop_index('ix_sends_user_sent')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_index('ix_replies_user_id')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index('ix_followups_status')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_id')

    # ### end Alembic commands ###
