"""add followup v2 tables

Revision ID: c83e5bf58a66
Revises: b2c3d4e5f6a7
Create Date: 2026-03-27 19:02:58.368821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83e5bf58a66'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # Create new follow-up v2 tables
    op.create_table('followup_contacts',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('workspace_id', sa.String(36), sa.ForeignKey('workspaces.id'), nullable=False),
        sa.Column('contact_email', sa.String(255), nullable=False),
        sa.Column('contact_name', sa.String(255)),
        sa.Column('company_name', sa.String(255)),
        sa.Column('state', sa.String(20), nullable=False, server_default='active'),
        sa.Column('stage', sa.String(30), nullable=False, server_default='fu1_scheduled'),
        sa.Column('is_followup_enabled', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')),
        sa.Column('next_followup_at', sa.DateTime()),
        sa.Column('last_followup_sent_at', sa.DateTime()),
        sa.Column('last_reply_at', sa.DateTime()),
        sa.Column('last_activity_at', sa.DateTime()),
        sa.Column('initial_email_sent_at', sa.DateTime()),
        sa.Column('fu1_sent_at', sa.DateTime()),
        sa.Column('fu2_sent_at', sa.DateTime()),
        sa.Column('fu3_sent_at', sa.DateTime()),
        sa.Column('completed_fu3_at', sa.DateTime()),
        sa.Column('loads_at', sa.DateTime()),
        sa.Column('warm_at', sa.DateTime()),
        sa.Column('blocked_at', sa.DateTime()),
        sa.Column('closed_at', sa.DateTime()),
        sa.Column('paused_at', sa.DateTime()),
        sa.Column('resumed_at', sa.DateTime()),
        sa.Column('block_reason', sa.String(512)),
        sa.Column('pause_reason', sa.String(512)),
        sa.Column('close_reason', sa.String(512)),
        sa.Column('source_thread_id', sa.String(512)),
        sa.Column('source_reply_id', sa.String(512)),
        sa.Column('reply_subject', sa.String(512)),
        sa.Column('reply_msg_id', sa.String(512)),
        sa.Column('current_route', sa.String(512)),
        sa.Column('notes', sa.Text(), server_default=''),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
        sa.UniqueConstraint('workspace_id', 'contact_email', name='uq_fc_ws_email'),
    )
    op.create_index('ix_fc_ws_state', 'followup_contacts', ['workspace_id', 'state'])
    op.create_index('ix_fc_ws_stage', 'followup_contacts', ['workspace_id', 'stage'])
    op.create_index('ix_fc_ws_next', 'followup_contacts', ['workspace_id', 'next_followup_at'])
    op.create_index('ix_fc_user_state', 'followup_contacts', ['user_id', 'state'])

    op.create_table('followup_events',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('followup_contact_id', sa.String(36),
                  sa.ForeignKey('followup_contacts.id', ondelete='CASCADE'), nullable=False),
        sa.Column('workspace_id', sa.String(36), sa.ForeignKey('workspaces.id')),
        sa.Column('event_type', sa.String(30), nullable=False),
        sa.Column('from_state', sa.String(20)),
        sa.Column('to_state', sa.String(20)),
        sa.Column('from_stage', sa.String(30)),
        sa.Column('to_stage', sa.String(30)),
        sa.Column('event_at', sa.DateTime(), nullable=False),
        sa.Column('actor_type', sa.String(20), nullable=False),
        sa.Column('actor_user_id', sa.String(36)),
        sa.Column('metadata_json', sa.Text()),
        sa.Column('notes', sa.String(512)),
    )
    op.create_index('ix_fe_contact_at', 'followup_events', ['followup_contact_id', 'event_at'])

    op.create_table('followup_settings',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('workspace_id', sa.String(36), sa.ForeignKey('workspaces.id'),
                  unique=True, nullable=False),
        sa.Column('fu1_delay_days', sa.Integer(), nullable=False, server_default='3'),
        sa.Column('fu2_delay_days', sa.Integer(), nullable=False, server_default='5'),
        sa.Column('fu3_delay_days', sa.Integer(), nullable=False, server_default='7'),
        sa.Column('auto_stop_on_reply', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')),
        sa.Column('default_followup_enabled', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.alter_column('token_expiry',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.alter_column('auto_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(TRUE)'))
        batch_op.alter_column('scheduled_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sends_user_status'))

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('fu_auto_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(TRUE)'))

    # ### end Alembic commands ###


def downgrade():
    op.drop_index('ix_fe_contact_at', table_name='followup_events')
    op.drop_table('followup_events')
    op.drop_index('ix_fc_user_state', table_name='followup_contacts')
    op.drop_index('ix_fc_ws_next', table_name='followup_contacts')
    op.drop_index('ix_fc_ws_stage', table_name='followup_contacts')
    op.drop_index('ix_fc_ws_state', table_name='followup_contacts')
    op.drop_table('followup_contacts')
    op.drop_table('followup_settings')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('fu_auto_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(TRUE)'))

    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sends_user_status'), ['user_id', 'status'], unique=False)

    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.alter_column('scheduled_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('auto_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(TRUE)'))

    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.alter_column('token_expiry',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
